/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type ProjectReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'project';
};

export type Skill = {
  _id: string;
  _type: 'skill';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  category: 'frontend' | 'backend' | 'data' | 'cloud' | 'tools';
  usage: 'daily' | 'regular' | 'familiar';
  projects?: Array<
    {
      _key: string;
    } & ProjectReference
  >;
};

export type Experience = {
  _id: string;
  _type: 'experience';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  position: InternationalizedArrayString;
  organisation: string;
  location?: string;
  startDate?: string;
  endDate?: string;
  description?: InternationalizedArrayText;
  achievements?: Array<
    {
      _key: string;
    } & Bullet
  >;
  technologies?: Array<string>;
};

export type InternationalizedArrayText = Array<
  {
    _key: string;
  } & InternationalizedArrayTextValue
>;

export type InternationalizedArrayString = Array<
  {
    _key: string;
  } & InternationalizedArrayStringValue
>;

export type Service = {
  _id: string;
  _type: 'service';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  number: number;
  stage: 'understand' | 'architect' | 'build' | 'measure' | 'improve';
  title: string;
  description: InternationalizedArrayText;
  keywords?: Array<string>;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset';
};

export type Project = {
  _id: string;
  _type: 'project';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary?: InternationalizedArrayText;
  year?: number;
  client?: string;
  role?: InternationalizedArrayString;
  featured?: boolean;
  order?: number;
  stack?: Array<string>;
  images?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: InternationalizedArrayString;
    _type: 'image';
    _key: string;
  }>;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  context?: InternationalizedArrayText;
  constraint?: InternationalizedArrayString;
  decisions?: Array<
    {
      _key: string;
    } & Bullet
  >;
  outcomes?: Array<
    {
      _key: string;
    } & Outcome
  >;
};

export type SanityImageCrop = {
  _type: 'sanity.imageCrop';
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot';
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: 'slug';
  current: string;
  source?: string;
};

export type Settings = {
  _id: string;
  _type: 'settings';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: InternationalizedArrayString;
  description: InternationalizedArrayText;
  ogImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: 'image';
  };
};

export type SanityFileAssetReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'sanity.fileAsset';
};

export type Profile = {
  _id: string;
  _type: 'profile';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  role: InternationalizedArrayString;
  location?: string;
  bio?: InternationalizedArrayText;
  photo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: InternationalizedArrayString;
    _type: 'image';
  };
  available?: boolean;
  links?: Array<
    {
      _key: string;
    } & Link
  >;
  resumeFr?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
  resumeEn?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  };
};

export type Outcome = {
  _type: 'outcome';
  value: string;
  label: InternationalizedArrayString;
};

export type Link = {
  _type: 'link';
  label: string;
  url: string;
};

export type Bullet = {
  _type: 'bullet';
  text: InternationalizedArrayString;
};

export type TranslationMetadata = {
  _id: string;
  _type: 'translation.metadata';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  translations?: InternationalizedArrayReference;
  schemaTypes?: Array<string>;
};

export type InternationalizedArrayReference = Array<
  {
    _key: string;
  } & InternationalizedArrayReferenceValue
>;

export type PostReference = {
  _ref: string;
  _type: 'reference';
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: 'post';
};

export type InternationalizedArrayReferenceValue = {
  _type: 'internationalizedArrayReferenceValue';
  value?: PostReference;
  language: string;
};

export type Post = {
  _id: string;
  _type: 'post';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  language?: string;
  title: string;
  slug: Slug;
  summary?: string;
  publishedAt: string;
  cover?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  };
  tags?: Array<string>;
  pinned?: boolean;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'normal' | 'h2' | 'h3' | 'blockquote';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
    | {
        language?:
          | 'typescript'
          | 'tsx'
          | 'javascript'
          | 'json'
          | 'bash'
          | 'css'
          | 'html'
          | 'yaml'
          | 'markdown'
          | 'text';
        code?: string;
        _type: 'codeBlock';
        _key: string;
      }
  >;
};

export type InternationalizedArrayTextValue = {
  _type: 'internationalizedArrayTextValue';
  value?: string;
  language: string;
};

export type InternationalizedArrayStringValue = {
  _type: 'internationalizedArrayStringValue';
  value?: string;
  language: string;
};

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch';
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: 'sanity.imagePalette';
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions';
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata';
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: 'sanity.fileAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData';
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: 'sanity.imageAsset';
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: 'geopoint';
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | ProjectReference
  | Skill
  | Experience
  | InternationalizedArrayText
  | InternationalizedArrayString
  | Service
  | SanityImageAssetReference
  | Project
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | Settings
  | SanityFileAssetReference
  | Profile
  | Outcome
  | Link
  | Bullet
  | TranslationMetadata
  | InternationalizedArrayReference
  | PostReference
  | InternationalizedArrayReferenceValue
  | Post
  | InternationalizedArrayTextValue
  | InternationalizedArrayStringValue
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/queries/posts.ts
// Variable: POSTS_QUERY
// Query: *[_type == "post" && language == $language && defined(publishedAt)]    | order(pinned desc, publishedAt desc) {    _id,    title,    "slug": slug.current,    summary,    publishedAt,    tags,    pinned,    cover  }
export type POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  publishedAt: string;
  tags: Array<string> | null;
  pinned: boolean | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
}>;

// Source: src/sanity/queries/posts.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == "post" && language == $language && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    summary,    publishedAt,    tags,    cover,    body  }
export type POST_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  publishedAt: string;
  tags: Array<string> | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: 'image';
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: 'span';
          _key: string;
        }>;
        style?: 'blockquote' | 'h2' | 'h3' | 'normal';
        listItem?: 'bullet' | 'number';
        markDefs?: Array<{
          href?: string;
          _type: 'link';
          _key: string;
        }>;
        level?: number;
        _type: 'block';
        _key: string;
      }
    | {
        language?:
          | 'bash'
          | 'css'
          | 'html'
          | 'javascript'
          | 'json'
          | 'markdown'
          | 'text'
          | 'tsx'
          | 'typescript'
          | 'yaml';
        code?: string;
        _type: 'codeBlock';
        _key: string;
      }
    | {
        asset?: SanityImageAssetReference;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt?: string;
        _type: 'image';
        _key: string;
      }
  > | null;
} | null;

// Source: src/sanity/queries/profile.ts
// Variable: PROFILE_QUERY
// Query: *[_type == "profile"][0] {    name,    "role": role[language == $language][0].value,    location,    "bio": bio[language == $language][0].value,    "photo": photo{      ...,      "alt": alt[language == $language][0].value    },    available,    links,    resumeFr,    resumeEn  }
export type PROFILE_QUERY_RESULT = {
  name: string;
  role: string | null;
  location: string | null;
  bio: string | null;
  photo: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: 'image';
  } | null;
  available: boolean | null;
  links: Array<
    {
      _key: string;
    } & Link
  > | null;
  resumeFr: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  } | null;
  resumeEn: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: 'file';
  } | null;
} | null;

// Source: src/sanity/queries/projects.ts
// Variable: PROJECTS_QUERY
// Query: *[_type == "project"] | order(order asc, year desc) {    _id,    title,    "slug": slug.current,    "summary": summary[language == $language][0].value,    year,    client,    "role": role[language == $language][0].value,    featured,    stack,    "cover": images[0]{      ...,      "alt": alt[language == $language][0].value    },    links  }
export type PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  year: number | null;
  client: string | null;
  role: string | null;
  featured: boolean | null;
  stack: Array<string> | null;
  cover: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: 'image';
    _key: string;
  } | null;
  links: Array<
    {
      _key: string;
    } & Link
  > | null;
}>;

// Source: src/sanity/queries/projects.ts
// Variable: FEATURED_PROJECTS_QUERY
// Query: *[_type == "project" && featured == true] | order(order asc, year desc) [0...4] {    _id,    title,    "slug": slug.current,    "summary": summary[language == $language][0].value,    year,    client,    stack  }
export type FEATURED_PROJECTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  year: number | null;
  client: string | null;
  stack: Array<string> | null;
}>;

// Source: src/sanity/queries/projects.ts
// Variable: PROJECT_BY_SLUG_QUERY
// Query: *[_type == "project" && slug.current == $slug][0] {    _id,    title,    "slug": slug.current,    "summary": summary[language == $language][0].value,    year,    client,    "role": role[language == $language][0].value,    stack,    images[]{      ...,      "alt": alt[language == $language][0].value    },    links,    "context": context[language == $language][0].value,    "constraint": constraint[language == $language][0].value,    "decisions": decisions[]{ "text": text[language == $language][0].value },    outcomes[]{      value,      "label": label[language == $language][0].value    }  }
export type PROJECT_BY_SLUG_QUERY_RESULT = {
  _id: string;
  title: string;
  slug: string;
  summary: string | null;
  year: number | null;
  client: string | null;
  role: string | null;
  stack: Array<string> | null;
  images: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string | null;
    _type: 'image';
    _key: string;
  }> | null;
  links: Array<
    {
      _key: string;
    } & Link
  > | null;
  context: string | null;
  constraint: string | null;
  decisions: Array<{
    text: string | null;
  }> | null;
  outcomes: Array<{
    value: string;
    label: string | null;
  }> | null;
} | null;

// Source: src/sanity/queries/services.ts
// Variable: SERVICES_QUERY
// Query: *[_type == "service"] | order(number asc) {    _id,    number,    stage,    title,    "description": description[language == $language][0].value,    keywords  }
export type SERVICES_QUERY_RESULT = Array<{
  _id: string;
  number: number;
  stage: 'architect' | 'build' | 'improve' | 'measure' | 'understand';
  title: string;
  description: string | null;
  keywords: Array<string> | null;
}>;

// Query TypeMap
declare global {
  interface SanityQueries {
    '\n  *[_type == "post" && language == $language && defined(publishedAt)]\n    | order(pinned desc, publishedAt desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedAt,\n    tags,\n    pinned,\n    cover\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[_type == "post" && language == $language && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    summary,\n    publishedAt,\n    tags,\n    cover,\n    body\n  }\n': POST_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "profile"][0] {\n    name,\n    "role": role[language == $language][0].value,\n    location,\n    "bio": bio[language == $language][0].value,\n    "photo": photo{\n      ...,\n      "alt": alt[language == $language][0].value\n    },\n    available,\n    links,\n    resumeFr,\n    resumeEn\n  }\n': PROFILE_QUERY_RESULT;
    '\n  *[_type == "project"] | order(order asc, year desc) {\n    _id,\n    title,\n    "slug": slug.current,\n    "summary": summary[language == $language][0].value,\n    year,\n    client,\n    "role": role[language == $language][0].value,\n    featured,\n    stack,\n    "cover": images[0]{\n      ...,\n      "alt": alt[language == $language][0].value\n    },\n    links\n  }\n': PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && featured == true] | order(order asc, year desc) [0...4] {\n    _id,\n    title,\n    "slug": slug.current,\n    "summary": summary[language == $language][0].value,\n    year,\n    client,\n    stack\n  }\n': FEATURED_PROJECTS_QUERY_RESULT;
    '\n  *[_type == "project" && slug.current == $slug][0] {\n    _id,\n    title,\n    "slug": slug.current,\n    "summary": summary[language == $language][0].value,\n    year,\n    client,\n    "role": role[language == $language][0].value,\n    stack,\n    images[]{\n      ...,\n      "alt": alt[language == $language][0].value\n    },\n    links,\n    "context": context[language == $language][0].value,\n    "constraint": constraint[language == $language][0].value,\n    "decisions": decisions[]{ "text": text[language == $language][0].value },\n    outcomes[]{\n      value,\n      "label": label[language == $language][0].value\n    }\n  }\n': PROJECT_BY_SLUG_QUERY_RESULT;
    '\n  *[_type == "service"] | order(number asc) {\n    _id,\n    number,\n    stage,\n    title,\n    "description": description[language == $language][0].value,\n    keywords\n  }\n': SERVICES_QUERY_RESULT;
  }
}
// Lets @sanity/client releases that predate the global registry read it too
declare module '@sanity/client' {
  interface SanityQueries extends globalThis.SanityQueries {}
}
